### ISSUE TITLE
Assets is not created

### ISSUE THREAD

**Issue by boynux** [svenstaro/upload-release-action#101]
Hi,

Thanks for creating this action. Recently I tried to use this actions but the assets won't appear in releases. Here is my simple workflow:
https://github.com/boynux/squid-exporter/blob/master/.github/workflows/release.yml

For convenience:
```
...
release:
    runs-on: ubuntu-latest

    steps:
      - name: Download binaries for release
        uses: actions/download-artifact@master
        with:
          name: binary
          path: bin/squid-exporter

      - name: Release latest version
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: squid-exporter
          file: bin/squid-exporter
          tag: unstable
          overwrite: true
          body: "pre-release"
          prerelease: true
...
```

The release is created, however the `squid-exporter` asset is not uploaded. There is no error in the workflow to debug.

**Comment by JonasVautherin** [comment]
Did you find a solution? It happens for me from a reusable workflow. The step says that it succeeded, with output:

```
Run svenstaro/upload-release-action@v2
  with:
    repo_token: ***
    file_glob: true
    file: libmavlink-dev_amd64
    asset_name: libmavlink-dev_amd64.deb
    tag: refs/tags/v1.0-1
    overwrite: true
```

However the artifacts are not published to the release on the calling repo. I would expect the action to fail if... well if it failed to upload the files. Not sure what's happening there...
