### ISSUE TITLE
`draft: true` creates new releases for each asset uploaded by matrix build

### ISSUE THREAD

**Issue by dxrcy** [svenstaro/upload-release-action#133]
When using a matrix job, a new release is created for each time a matrix job uploads an asset, instead of including asset in the existing release with the same tag, name, etc.

If I remove the `draft: true` line, it adds all assets to the same release as expected.

```yml
name: Publish release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: ${{ github.event.repository.name }}
            asset_name: ${{ github.event.repository.name }}-linux-amd64
          - os: windows-latest
            artifact_name: ${{ github.event.repository.name }}.exe
            asset_name: ${{ github.event.repository.name }}-windows-amd64.exe
          - os: macos-latest
            artifact_name: ${{ github.event.repository.name }}
            asset_name: ${{ github.event.repository.name }}-macos-amd64

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: cargo build --release --locked --verbose

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
        draft: true # HERE
```

With some testing, I believe `draft: true` is the only field which causes this behaviour.

Without using `draft: true`:
![Image](https://github.com/user-attachments/assets/d5cbb858-84b8-47fa-a693-2f1057b2938c)

Using `draft: true`: (ignore differences in title, tag)
![Image](https://github.com/user-attachments/assets/f4bfa509-b8bc-4734-a6b5-683352b41443)

I could not find any explanation for this or existing issues, so I can't imagine this is intended behaviour.
