### ISSUE TITLE
Release Body file read fails

### ISSUE THREAD

**Issue by celguar** [svenstaro/upload-release-action#134]
https://github.com/celguar/spp-classics-cmangos/actions/runs/13871910729/job/38819823697
/home/runner/work/_temp/44c83cf2-18bd-4743-8598-984db20088e5.sh: line 1: /home/runner/work/spp-classics-cmangos/spp-classics-cmangos/README.md: Permission denied

code itself

```
steps:
      - uses: actions/checkout@v3
    
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: snapshot-${{env.CORE_EXPANSION}}
          path: all_snapshots

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Read README.md and use it as a body of new release
        id: read_release
        shell: bash
        run: |
          r=$(${{github.workspace}}/README.md)              # <--- Read README.md (Provide correct path as per your repo)
          r="${r//'%'/'%25'}"                               # Multiline escape sequences for %
          r="${r//$'\n'/'%0A'}"                             # Multiline escape sequences for '\n'
          r="${r//$'\r'/'%0D'}"                             # Multiline escape sequences for '\r'
          echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT          # <--- Set environment variable
```
