### ISSUE TITLE
Can't find an example for using multiple files with different file paths

### ISSUE THREAD

**Issue by kaizoku-oh** [svenstaro/upload-release-action#16]
Is there an example for using multiple files with different paths and filenames?

example: 
```
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}

        file: .pio/build/esp32dev/firmware_esp32dev.bin
        asset_name: firmware_esp32dev.bin

        file: .pio/build/nodemcuv2/firmware_nodemcuv2.bin
        asset_name: firmware_nodemcuv2.bin

        tag: ${{ github.ref }}
        overwrite: true
```

**Comment by kaizoku-619** [comment]
I solved the problem:
```
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: .pio/build/*/firmware_*.bin
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
```
