### ISSUE TITLE
@1.0.1 / error / file_glob invalid

### ISSUE THREAD

**Issue by nerdCopter** [svenstaro/upload-release-action#17]
`Unexpected input 'file_glob', valid inputs are ['repo_token', 'file', 'asset_name', 'tag', 'overwrite']`
`Input required and not supplied: asset_name`

````
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@1.0.1
      if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'ref/head/master')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: obj/*.hex
        #asset_name: ignored
        tag: ${{ github.ref }}
        overwrite: false
        file_glob: true
```

it works with @v1

However, i need a "Draft", my testing of this went to a live release :(
