### ISSUE TITLE
Action successful but now showing up under assets in release

### ISSUE THREAD

**Issue by nnofel** [svenstaro/upload-release-action#22]
The action shows that it is finished successfully but the asset uploaded doesn't show under the Release

**Comment by svenstaro** [comment]
Does the log say anything?

**Comment by nnofel** [comment]
<img width="1185" alt="Screenshot 2020-07-31 at 16 01 14" src="https://user-images.githubusercontent.com/67900174/89042448-3f845f80-d347-11ea-8907-6d697b778c77.png">

**Comment by svenstaro** [comment]
Did the release already exist?

**Comment by nnofel** [comment]
@svenstaro yes it did. In fact my workflow gets triggered on the create release event.

**Comment by iwishiwasaneagle** [comment]
Same issue on my end 
```
      - name: Upload the release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: main.pdf
          overwrite: true
          asset_name: "${{needs.setup-envs.outputs.tag-name}}.pdf"
          release_name: "${{needs.setup-envs.outputs.tag-name}}"
          body: "${{ needs.setup-envs.outputs.release_body }}"
```
