### ISSUE TITLE
[feature-request] Create a GH release in a foreign repository

### ISSUE THREAD

**Issue by kittaakos** [svenstaro/upload-release-action#24]
I would like to use this action to create a GH release in a foreign repository. I have access to the foreign repository. I do not know if it's possible to achieve it with GH Actions in general, but I thought it worth a feature request.

Use case:
 - There is a private GH repo that hosts the source code. GH Actions workflows are configured in the private repository.
 - There is a public repository where the users can log issues and can download the releases. They do not (yet) see the source code.

Current workflow:
 - GH Actions is used to create the GH releases in the private repository.
 - The corresponding GH release has to be created manually in the public repo and the artifacts have to be upload.

I would like to create a GH release in the public repo from a workflow triggered by the private repository.

For example, the [_GitHub Release task_](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops) can do this on Azure. Would it be possible to achieve something with this action? There is a [`repositoryName`](https://github.com/microsoft/azure-pipelines-tasks/blob/7267ee89614b006a286f5a34db51bdfba1e2228d/Tasks/GitHubReleaseV1/task.json#L39-L50) property, that defaults to the current repo.

The config would be something like this:
```yaml
  - name: Publish Release [GitHub]
    uses: svenstaro/upload-release-action@v1-release
    with:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
      repository_name: owner/foreign-repository-name
      file: dist/*
      tag: ${{ github.ref }}
      file_glob: true
```

Thank you for this great action!
