### ISSUE TITLE
Environment Variable in File Name

### ISSUE THREAD

**Issue by Myoldmopar** [svenstaro/upload-release-action#30]
It could be more of a design question, but are environment variables supposed to be applied in the name field?

This was a snippet from my workflow:
```
    - name: Upload SH to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{runner.workspace}}/EnergyPlus/build/${{ matrix.os }}_$PACKAGE_NAME_SH
        tag: ${{ github.ref }}
        overwrite: true
```

The double bracketed things were of course filled in when the file was processed by Github.  The `$PACKAGE_NAME_SH` environment variable was set by using proper action commands dynamically just above this (`echo ::set-env name=PACKAGE_NAME_SH::...`).   But when this action ran, the `$PACKAGE_NAME_SH` was left as-is, and of course, it couldn't find the package name which would have matched if that field had been replaced with the actual environment variable value.

Right now I can get it to work if I just file glob for the artifact name, but it zips the single file up, and I want the package uploaded in raw form.  I'm trying to dynamically specify the exact filename and just need this environment variable to be populated with its value.

Thanks!
