### ISSUE TITLE
How to trigger the workflow

### ISSUE THREAD

**Issue by Tejas2805** [svenstaro/upload-release-action#32]
I have committed the workflow file but not sure about how to trigger the workflow. I have already created a tag and a release.

**Comment by svenstaro** [comment]
If you want it to trigger on new tags, try using
```
on:
  push:
    tags:
      - '*'
```
See `README.md` for more examples.
