### ISSUE TITLE
Can not release ".app" files on macos

### ISSUE THREAD

**Issue by FlamingTuri** [svenstaro/upload-release-action#56]
I am trying to deploy assets for linux, windows and mac following the README example. However the action terminates with different error messages when releasing the mac asset: 

1. Error: request to https://uploads.github.com/repos/FlamingTuri/test/releases/48849361/assets?name=main-macos.app& failed, reason: write EPIPE
    ```
    {"message":"Bad Content-Length: ","request_id":"BB46:0F6B:249001:2D594B:612FF778"}
    ```

2. Error: Validation Failed: {"resource":"ReleaseAsset","code":"custom","field":"name","message":"name has a file extension that is not allowed"}

3.  Error: request to https://uploads.github.com/repos/FlamingTuri/test/releases/48841901/assets?name=main-macos.app& failed, reason: socket hang up
    Which once again leads to a
    ```
    {"message":"Bad Content-Length: ","request_id":"ECBC:37A3:D1831F:E886C4:612FFC47"}
    ```

This is my yaml workflow:

```yml
name: release-artifacts

on: release

jobs:
  release:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifactName: main-linux
          - os: windows-latest
            artifactName: main-windows.exe
          - os: macos-latest
            artifactName: main-macos.app
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: node .github/script/create-asset.mjs ${{ matrix.artifactName }}
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: server/dist/${{ matrix.artifactName }}
          asset_name: ${{ matrix.artifactName }}
          tag: ${{ github.ref }}
          overwrite: true
```

Moreover, everything works smoothely if I delete the ".app" extension.

Since some errors are due to content length, could they be caused by bug in the node runtime used by the action? I had other issues with node 12 (mainly involving speed) on mac actions.
