### ISSUE TITLE
Delete release and create new one?

### ISSUE THREAD

**Issue by probonopd** [svenstaro/upload-release-action#59]
Is it possible to delete an existing release (if one with the same name already exsits) and create a new one?
`overwrite: true` seems not do do this for me.

**Comment by lukebarone** [comment]
I'm having the same issue.

```yaml
    # Add it as a release
    - name: Publish release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.DEPLOY_KEY }}
        file: FILENAME.zip
        asset_name: FILENAME.zip
        tag: master
        overwrite: true
```

I attempted to zip it up first (worked). When running the action again, it throws  the `Validation Failed: {"resource":"ReleaseAsset","code":"already_exists","field":"name"}` error. Only using one file (linked item mentioned > 30 objects)
