### ISSUE TITLE
PreRelease doesn't seem to work

### ISSUE THREAD

**Issue by bassterror** [svenstaro/upload-release-action#60]
Everything seems to work as it should, but when I check the release in GitHub it isn't marked as "pre-release". Everything else is set correctly. Am I missing something?

My workflow:
```
jobs:
  build:
    runs-on: windows-latest

    env:
      Pre_Release: ${{ contains(github.ref, 'dev') }}

    steps:
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: MKVStudio.7z
          asset_name: MKVStudio.7z
          release_name: "${{ steps.gitversion.outputs.MajorMinorPatch }}"
          tag: "${{ steps.gitversion.outputs.MajorMinorPatch }}"
          overwrite: true
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          prerelease: $env:Pre_Release
```

Result in the log:
```
with:
    repo_token: ***
    file: MKVStudio.7z
    asset_name: MKVStudio.7z
    release_name: 0.6.0
    tag: 0.6.0
    overwrite: true
    body: - no changes
    prerelease: $env:Pre_Release
  env:
    Pre_Release: true
```
