### ISSUE TITLE
Please retry read ECONNRESET

### ISSUE THREAD

**Issue by abcfy2** [svenstaro/upload-release-action#62]
Here is my fail: https://github.com/abcfy2/qBittorrent-Enhanced-Edition/runs/4746010908?check_suite_focus=true

```
Run svenstaro/upload-release-action@v2
  with:
    repo_token: ***
    file: .github/workflows/qbittorrent-enhanced-nox_arm-linux-musleabi_static.zip
    tag: refs/tags/v4.4.0.11
    overwrite: true
/usr/bin/docker exec  9a91c2cc94ac097115ffd1249a0849d80ee97c1b5da000097cb9659eb9176bc1 sh -c "cat /etc/*release | grep ^ID"
Error: request to https://uploads.github.com/repos/abcfy2/qBittorrent-Enhanced-Edition/releases/56650008/assets?name=qbittorrent-enhanced-nox_arm-linux-musleabi_static.zip& failed, reason: read ECONNRESET
```

**Comment by lil5** [comment]
I've had the same issue for more information I ran a job inside a docker container, like so:

```
  build_and_upload_linux:
    runs-on: ubuntu-latest
    container:
      image: lil5/my-docker-image:1.0.0
      options: --privileged
```

@abcfy2 Did you do something like this too?
