### ISSUE TITLE
Assertion `(ret) != (nullptr)' failed

### ISSUE THREAD

**Issue by patrickelectric** [svenstaro/upload-release-action#66]
```
Run svenstaro/upload-release-action@v[2](https://github.com/bluerobotics/BlueOS-docker/runs/5428302399?check_suite_focus=true#step:6:2)
  with:
    repo_token: ***
    file: BlueOS-raspberry.zip
    tag: refs/tags/1.0.0-beta.14
    overwrite: true
    prerelease: true
```
I'm getting:
 /home/pi/actions-runner/externals/node12/bin/node[13726]: ../src/env-inl.h:949:char* node::Environment::Allocate(size_t): Assertion `(ret) != (nullptr)' failed.

The file is around 1GB.
