### ISSUE TITLE
Zipped file loses some memory

### ISSUE THREAD

**Issue by Moosems** [svenstaro/upload-release-action#77]
I set up an action to build and compile a mac application. It then zips this file and adds it to a release using this action. When I do these actions the exact same way on my computer manually it works fine but when the action is used and uploads the file it gives the following error message indicating that files and info is missing when run

Error:
```Traceback
/Users/Moosems/Downloads/DIP.app/Contents/MacOS/DIP ; exit;
Moosems-MBP:~ Moosems$ /Users/Moosems/Downloads/DIP.app/Contents/MacOS/DIP ; exit;
[6583] Error loading Python lib '/Users/Moosems/Downloads/DIP.app/Contents/MacOS/Python': dlopen: dlopen(/Users/moosems/Downloads/DIP.app/Contents/MacOS/Python, 10): Symbol not found: _preadv
  Referenced from: /Users/Moosems/Downloads/DIP.app/Contents/MacOS/Python (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/Moosems/Downloads/DIP.app/Contents/MacOS/Python
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

Action file:
```yml
name: Build and package Mac version

on:
  push:
    branches:
      main
  pull_request:
    branches: 
     main

jobs:
  build-app:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install requirements
      run: pip3 install pyinstaller

    - name: Build
      run: pyinstaller DIP.spec
      
    - name: Log files
      run: |
        ls dist
        ls dist/DIP
        cd dist; zip -0 -r -y DIP.app.zip DIP.app

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.TOKEN }}
        file: dist/DIP.app.zip
        asset_name: DIP.app.zip
        tag: latest-mac-build
        overwrite: true
```
